In [2]:
import pandas as pd 
import numpy as np
from pathlib import Path

In [3]:
healthyPath = Path("../dataset/balanceDataset/Healthy")
filesHealthy = list(healthyPath.glob("*.csv"))
len(filesHealthy)
df = pd.read_csv(filesHealthy[0])

In [4]:
df.head(5)

,Time,GeneralEvent,ClinicalEvent,L Foot Contact,R Foot Contact,L Foot Pressure,R Foot Pressure,Walkway_X,Walkway_Y,WalkwayPressureLevel,...,RPressure16,Rinsole:Acc_X,Rinsole:Acc_Y,Rinsole:Acc_Z,Rinsole:Gyr_X,Rinsole:Gyr_Y,Rinsole:Gyr_Z,RTotalForce,RCoP_X,RCoP_Y
0,0 sec,unlabeled,unlabeled,0,0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.01 sec,unlabeled,unlabeled,0,0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.02 sec,unlabeled,unlabeled,0,0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.03 sec,unlabeled,unlabeled,0,0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.04 sec,unlabeled,unlabeled,0,0,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.isnull().sum()

Time                0
GeneralEvent        0
ClinicalEvent       0
L Foot Contact      0
R Foot Contact      0
                 ...
Rinsole:Gyr_Y     276
Rinsole:Gyr_Z     276
RTotalForce       276
RCoP_X            276
RCoP_Y            276
Length: 347, dtype: int64

In [6]:
nullCount = df.isnull().sum()

In [7]:
nullCount[nullCount > 0]

Walkway_X               3270
Walkway_Y               3270
WalkwayPressureLevel    3270
WalkwayFoot             3270
L_Ankle_Acc_X           1193
                        ...
Rinsole:Gyr_Y            276
Rinsole:Gyr_Z            276
RTotalForce              276
RCoP_X                   276
RCoP_Y                   276
Length: 76, dtype: int64

In [8]:
print("total rows: ", len(df))
print("cols with missing values:", (df.isnull().sum()>0).sum())

total rows:  9221
cols with missing values: 76

In [9]:
missingPerc = (df.isnull().sum() / len(df)) * 100

In [10]:
missingPerc[missingPerc > 0]

Walkway_X               35.462531
Walkway_Y               35.462531
WalkwayPressureLevel    35.462531
WalkwayFoot             35.462531
L_Ankle_Acc_X           12.937859
                          ...
Rinsole:Gyr_Y            2.993168
Rinsole:Gyr_Z            2.993168
RTotalForce              2.993168
RCoP_X                   2.993168
RCoP_Y                   2.993168
Length: 76, dtype: float64

In [11]:
[col for col in df.columns if "Acc" in col or "Gry" in col]

['LowerBack_Acc_X',
 'LowerBack_Acc_Y',
 'LowerBack_Acc_Z',
 'LowerBack_FreeAcc_E',
 'LowerBack_FreeAcc_N',
 'LowerBack_FreeAcc_U',
 'R_Wrist_Acc_X',
 'R_Wrist_Acc_Y',
 'R_Wrist_Acc_Z',
 'R_Wrist_FreeAcc_E',
 'R_Wrist_FreeAcc_N',
 'R_Wrist_FreeAcc_U',
 'L_Wrist_Acc_X',
 'L_Wrist_Acc_Y',
 'L_Wrist_Acc_Z',
 'L_Wrist_FreeAcc_E',
 'L_Wrist_FreeAcc_N',
 'L_Wrist_FreeAcc_U',
 'R_MidLatThigh_Acc_X',
 'R_MidLatThigh_Acc_Y',
 'R_MidLatThigh_Acc_Z',
 'R_MidLatThigh_FreeAcc_E',
 'R_MidLatThigh_FreeAcc_N',
 'R_MidLatThigh_FreeAcc_U',
 'L_MidLatThigh_Acc_X',
 'L_MidLatThigh_Acc_Y',
 'L_MidLatThigh_Acc_Z',
 'L_MidLatThigh_FreeAcc_E',
 'L_MidLatThigh_FreeAcc_N',
 'L_MidLatThigh_FreeAcc_U',
 'R_LatShank_Acc_X',
 'R_LatShank_Acc_Y',
 'R_LatShank_Acc_Z',
 'R_LatShank_FreeAcc_E',
 'R_LatShank_FreeAcc_N',
 'R_LatShank_FreeAcc_U',
 'L_LatShank_Acc_X',
 'L_LatShank_Acc_Y',
 'L_LatShank_Acc_Z',
 'L_LatShank_FreeAcc_E',
 'L_LatShank_FreeAcc_N',
 'L_LatShank_FreeAcc_U',
 'R_DorsalFoot_Acc_X',
 'R_DorsalFoot_Acc_Y',
 'R_DorsalFoot_Acc_Z',
 'R_DorsalFoot_FreeAcc_E',
 'R_DorsalFoot_FreeAcc_N',
 'R_DorsalFoot_FreeAcc_U',
 'L_DorsalFoot_Acc_X',
 'L_DorsalFoot_Acc_Y',
 'L_DorsalFoot_Acc_Z',
 'L_DorsalFoot_FreeAcc_E',
 'L_DorsalFoot_FreeAcc_N',
 'L_DorsalFoot_FreeAcc_U',
 'R_Ankle_Acc_X',
 'R_Ankle_Acc_Y',
 'R_Ankle_Acc_Z',
 'R_Ankle_FreeAcc_E',
 'R_Ankle_FreeAcc_N',
 'R_Ankle_FreeAcc_U',
 'L_Ankle_Acc_X',
 'L_Ankle_Acc_Y',
 'L_Ankle_Acc_Z',
 'L_Ankle_FreeAcc_E',
 'L_Ankle_FreeAcc_N',
 'L_Ankle_FreeAcc_U',
 'Xiphoid_Acc_X',
 'Xiphoid_Acc_Y',
 'Xiphoid_Acc_Z',
 'Xiphoid_FreeAcc_E',
 'Xiphoid_FreeAcc_N',
 'Xiphoid_FreeAcc_U',
 'Forehead_Acc_X',
 'Forehead_Acc_Y',
 'Forehead_Acc_Z',
 'Forehead_FreeAcc_E',
 'Forehead_FreeAcc_N',
 'Forehead_FreeAcc_U',
 'Linsole:Acc_X',
 'Linsole:Acc_Y',
 'Linsole:Acc_Z',
 'Rinsole:Acc_X',
 'Rinsole:Acc_Y',
 'Rinsole:Acc_Z']

In [12]:
[col for col in df.columns if "Wrist" in col and "Gyr" in col]

['R_Wrist_Gyr_X',
 'R_Wrist_Gyr_Y',
 'R_Wrist_Gyr_Z',
 'L_Wrist_Gyr_X',
 'L_Wrist_Gyr_Y',
 'L_Wrist_Gyr_Z']

In [13]:
[col for col in df.columns if "Wrist" in col]

['R_Wrist_Acc_X',
 'R_Wrist_Acc_Y',
 'R_Wrist_Acc_Z',
 'R_Wrist_FreeAcc_E',
 'R_Wrist_FreeAcc_N',
 'R_Wrist_FreeAcc_U',
 'R_Wrist_Gyr_X',
 'R_Wrist_Gyr_Y',
 'R_Wrist_Gyr_Z',
 'R_Wrist_Mag_X',
 'R_Wrist_Mag_Y',
 'R_Wrist_Mag_Z',
 'R_Wrist_VelInc_X',
 'R_Wrist_VelInc_Y',
 'R_Wrist_VelInc_Z',
 'R_Wrist_OriInc_q0',
 'R_Wrist_OriInc_q1',
 'R_Wrist_OriInc_q2',
 'R_Wrist_OriInc_q3',
 'R_Wrist_Roll',
 'R_Wrist_Pitch',
 'R_Wrist_Yaw',
 'L_Wrist_Acc_X',
 'L_Wrist_Acc_Y',
 'L_Wrist_Acc_Z',
 'L_Wrist_FreeAcc_E',
 'L_Wrist_FreeAcc_N',
 'L_Wrist_FreeAcc_U',
 'L_Wrist_Gyr_X',
 'L_Wrist_Gyr_Y',
 'L_Wrist_Gyr_Z',
 'L_Wrist_Mag_X',
 'L_Wrist_Mag_Y',
 'L_Wrist_Mag_Z',
 'L_Wrist_VelInc_X',
 'L_Wrist_VelInc_Y',
 'L_Wrist_VelInc_Z',
 'L_Wrist_OriInc_q0',
 'L_Wrist_OriInc_q1',
 'L_Wrist_OriInc_q2',
 'L_Wrist_OriInc_q3',
 'L_Wrist_Roll',
 'L_Wrist_Pitch',
 'L_Wrist_Yaw']

In [14]:
df = pd.read_csv(filesHealthy[0])

In [16]:
balance_features = [
    "R_Wrist_Acc_X",
    "R_Wrist_Acc_Y",
    "R_Wrist_Acc_Z",
    "R_Wrist_Gyr_X",
    "R_Wrist_Gyr_Y",
    "R_Wrist_Gyr_Z"
]

In [17]:
sensor_df = df[balance_features].copy()

In [19]:
sensor_df.head(10)

,R_Wrist_Acc_X,R_Wrist_Acc_Y,R_Wrist_Acc_Z,R_Wrist_Gyr_X,R_Wrist_Gyr_Y,R_Wrist_Gyr_Z
0,8.688320,-3.877925,1.186262,0.074972,0.001967,0.008159
1,8.687842,-3.798477,1.208694,0.088235,-0.002621,-0.004497
2,8.731886,-3.606848,1.333566,0.074747,-0.017294,-0.010151
3,8.827163,-3.604369,1.424797,0.017824,-0.021206,-0.010283
4,8.755059,-3.835431,1.318061,-0.017508,-0.025875,-0.021818
5,8.755851,-3.981030,1.330298,-0.009442,-0.032407,-0.030512
6,8.827748,-3.926820,1.397436,-0.003842,-0.035760,-0.035285
7,8.851420,-3.929314,1.383717,-0.042792,-0.036915,-0.031080
8,8.841696,-4.145903,1.406429,-0.043555,-0.035217,-0.037844
9,8.835499,-4.233728,1.305791,-0.036419,-0.052862,-0.033466

In [20]:
sensor_df.isnull().sum()

R_Wrist_Acc_X    0
R_Wrist_Acc_Y    0
R_Wrist_Acc_Z    0
R_Wrist_Gyr_X    0
R_Wrist_Gyr_Y    0
R_Wrist_Gyr_Z    0
dtype: int64

In [21]:
np.isinf(sensor_df).sum()

R_Wrist_Acc_X    0
R_Wrist_Acc_Y    0
R_Wrist_Acc_Z    0
R_Wrist_Gyr_X    0
R_Wrist_Gyr_Y    0
R_Wrist_Gyr_Z    0
dtype: int64

In [22]:
sensor_df.describe()

,R_Wrist_Acc_X,R_Wrist_Acc_Y,R_Wrist_Acc_Z,R_Wrist_Gyr_X,R_Wrist_Gyr_Y,R_Wrist_Gyr_Z
count,9221.000000,9221.000000,9221.000000,9221.000000,9221.000000,9221.000000
mean,8.508500,-4.677607,1.108345,-0.007013,0.003958,-0.005864
std,0.645525,1.031779,0.726602,0.614827,0.235201,0.132744
min,4.533342,-13.657603,-9.121718,-13.942029,-1.145073,-0.867109
25%,8.195588,-5.227145,0.840452,-0.054274,-0.042254,-0.027797
50%,8.553230,-4.737260,1.111256,0.003927,-0.005536,-0.005149
75%,8.920978,-3.974147,1.361239,0.066852,0.025902,0.017734
max,12.769121,10.638203,9.304117,9.899535,3.787190,0.931218

In [62]:
def check_dataset(files, feature_cols):
    result = []
    for file in files:
        df = pd.read_csv(file, low_memory=False)
        missing_col = [col for col in feature_cols if col not in df.columns]

        if missing_col:
            result.append({
                'file': file.name,
                'missing_col': missing_col,
                'has_nan':None,
                'has_inf': None
            })
            continue

        sensor_df = df[feature_cols].apply(pd.to_numeric, errors = "coerce")

        result.append({
            "file": file.name,
            "missing_col": [],
            "has_nan": sensor_df.isnull().any().any(),
            "has_inf" : np.isinf(sensor_df).any().any()
        })

    return pd.DataFrame(result)

In [63]:
pdpath = Path("../dataset/balanceDataset/PD")
pdFiles = list(pdpath.glob("*.csv"))

In [64]:
print("healthy", len(filesHealthy))

healthy 85

In [65]:
print("PD", len(pdFiles))

PD 99

In [66]:
healthyCheck = check_dataset(filesHealthy, balance_features)
pdCheck = check_dataset(pdFiles, balance_features)

In [40]:
pdCheck[
    (pdCheck["has_nan"] == True) |
    (pdCheck["has_inf"] == True) |
    (pdCheck["missingCol"].apply(len) > 0)
]

Empty DataFrame
Columns: [file, missingCol, has_nan, has_inf]
Index: []

In [41]:
healthyCheck[
    (healthyCheck["has_nan"] == True) |
    (healthyCheck["has_inf"] == True) |
    (healthyCheck["missingCol"].apply(len) > 0)
]

Empty DataFrame
Columns: [file, missingCol, has_nan, has_inf]
Index: []